### ISSUE TITLE
How to define main triple in JF17k

### ISSUE THREAD

**Issue by PlusRoss** [migalkin/StarE#1]
Hi,

Thanks for the amazing work! May I ask how do you define the main triple and qualifiers in dataset JF17k? It seems that this dataset is unlike the other two datasets where the main triple and qualifiers are already provided as part of the data format.

**Comment by migalkin** [comment]
Hi, indeed, originally, JF17K resembles hypergraphs with one relation over several entities. 
In our work, we used JF17K processed by [Rosso et al](https://exascale.info/assets/pdf/rosso2020www.pdf) - the paper describes the methodology. The [HINGE repo](https://github.com/eXascaleInfolab/HINGE_code/) is available on Github

**Comment by PlusRoss** [comment]
Thanks for your prompt reply! However, I checked the paper and github repo but did not find how they transform the data. I may miss some information. If you know the methodology or the location of description in that paper, could you tell me it?

**Comment by migalkin** [comment]
Sorry for the delayed reply. 
I traced the citation history and believe the conversion procedure (hypergraph JF17K -> hyper-relational JF17K) stems from the work of [Guan et al](https://dl.acm.org/doi/10.1145/3308558.3313414) which is [NaLP](https://github.com/gsp2014/NaLP). Their github repo defines a conversion script, it might be what you are looking for.

Thanks!

**Comment by PlusRoss** [comment]
Thanks for your reply. It solves my problem!
