### ISSUE TITLE
I am wondering how can I save the model and load it?

### ISSUE THREAD

**Issue by 2258324319** [migalkin/StarE#12]
the structure of the code is too complex, I think maybe the "SAVE" in the config can help me to save the model, but I don't know how to load it for other test next time.

**Comment by geraltofrivia** [comment]
Hi, that's right the SAVE parameter when turned on triggers this code block [here](https://github.com/migalkin/StarE/blob/master/run.py#L317).

So could you check your working directory for some folder like `./models/{config['DATASET']}/{config['MODEL_NAME']}`?
