### ISSUE TITLE
Question about Figure 2.

### ISSUE THREAD

**Issue by SeongJinAhn** [migalkin/StarE#5]
I have a question about fig 2.
Is it correct to use ‘Q853077 mathematics’ rather than ‘Q413 physics’?

Cause einstein studied physics in university of zurich, I think the embedding of ‘univ of zurich’ should consider physics rather than mathematics.
Also, physics is written in the paragraph before fig 2.

Is there any thing that I’ve missed?

**Comment by geraltofrivia** [comment]
Hi @SeongJinAhn you are right in pointing out that the figure 2 label should be Q413 physics and not Q853077 mathematics. This is a slip up on our end. 

Thank you, so much, for pointing it out. We'll see if we can get the image fixed in the published paper, but I'm not sure if that's possible.

**Comment by SeongJinAhn** [comment]
Thank you!
It was so glad to see your works
